### ISSUE TITLE
Branch / Label policy

### ISSUE THREAD

**Issue by tyru** [tyru/caw.vim#53]
# TODO

* [x] Merge release branch (#42) (`master` will be HEAD branch and only merge PR)
  * [x] Move current PR's tasks into another issue (#58)
* [x] Delete announce label (#37)

# Reference

[GitHub branches policy in Vim plugin repository](http://tyru.hatenablog.com/entry/2016/03/28/235015)
